name: Develop Svc Gateway pipelines

on:
  push:
    branches:
      - develop
    
env:
  ENV: "dev"
  APP: "scv-gateway"

jobs:
  main:
    runs-on: ubuntu-latest
    environment: develop
    name: Develop Pipeline Svc Gateway
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get commit sha on PR Sync
        if: github.event_name == 'push'
        id: git-sha
        shell: bash
        run: |
          echo GIT_SHA=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        # Only worked for us with this option on
        with:
          install: true

      - name: Log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract metadata for docker
        if: github.event_name == 'push'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aeternity/smart-contract-verifier
          tags: |
            type=raw,value=develop,enable=${{ endsWith(GitHub.ref, 'develop') }}
      
      - name: Build and push docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/scv-gateway/dev/Dockerfile
          push: true
          target: prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps-aelabs.git
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: dev
          persist-credentials: false
          fetch-depth: 0

      - name: Latest Develop Branch Deploy on Push
        if: github.event_name == 'push'
        uses: aeternity/ae-github-actions/argocd-pr-sync@v4
        with: 
          git-sha: ${{ steps.git-sha.outputs.GIT_SHA }}
          url-prefix: develop
          env: ${{ env.ENV }}
          app: ${{ env.APP }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: aeternity/gitops-apps
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          branch: dev
