version: "3.8"
services:
  scv-gateway:
    build:
      context: .
      dockerfile: apps/scv-gateway/dev/Dockerfile
      target: dev
    command: ["node", "apps/scv-gateway/dev/docker-entry.dev.js"]
    volumes:
      - .:/usr/src/app
    restart: always
    ports:
      - '3000:3000'
  # scv-worker:
  #   build:
  #     context: .
  #     dockerfile: apps/scv-worker/dev/Dockerfile
  #     target: dev
  #   command: ["node", "apps/scv-worker/dev/docker-entry.dev.js"]
  #   volumes:
  #     - .:/usr/src/app
  #   restart: always
  #   ports:
  #     - '3001:3001'