export const SUPPORTED_LICENSES = [
  'None',
  'Unlicense',
  'MIT',
  'GNU GPLv2',
  'GNU GPLv3',
  'GNU LGPLv2.1',
  'GNU LGPLv3',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'MPL-2.0',
  'OSL-3.0',
  'Apache-2.0',
  'GNU AGPLv3',
  'BSL 1.1',
];
